version: '3.9'
services:
  api:
    build: .
    command: gunicorn --bind 0.0.0.0:5000 app:app
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
